CREATE TABLE taxes (
       id bigint GENERATED BY DEFAULT AS IDENTITY,
       country VARCHAR(50) NOT NULL,
       region VARCHAR(50),
       tax_percent DECIMAL(5,2) NOT NULL CHECK (tax_percent >= 0),
       tax_name VARCHAR(100) NOT NULL,
       start_date TIMESTAMP,
       end_date TIMESTAMP
);