create table auth_device_info
(
    id                  integer generated by default as identity primary key,
    device_name         varchar   not null,
    application_version varchar   not null,
    auth_time           timestamp not null,
    ip_address          varchar   not null,
    location            varchar   not null,
    client              uuid      not null references users(id)
);

