create table echeck(
                       id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       check_number varchar UNIQUE NOT NULL,
                       user_id uuid NOT NULL,
                       download_path varchar NOT NULL UNIQUE,
                       received_at timestamp NOT NULL
);