create table payment
(
    payment_id  integer generated by default as identity
        primary key,
    user_id     uuid not null,
    card_number varchar,
    total_price bigint,
    paid_at     timestamp
);