create table echeck(
                       id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       checkNumber varchar UNIQUE NOT NULL,
                       userId uuid NOT NULL,
                       downloadPath varchar NOT NULL UNIQUE,
                       receivedAt timestamp NOT NULL
);