CREATE TABLE prices (
                        id bigint GENERATED BY DEFAULT AS IDENTITY,
                        product_id bigint NOT NULL,
                        price double precision not null check (price > (0.0)::double precision),
                        currency VARCHAR(3) NOT NULL DEFAULT 'USD',
                        updated_at TIMESTAMP DEFAULT NOW()
);