create table email_confirmation
(
    id           integer generated by default as identity
        primary key,
    token        varchar,
    created_at   timestamp,
    expires_at   timestamp,
    confirmed_at timestamp,
    user_id      uuid
);