create table card
(
    card_id          integer generated by default as identity
        primary key,
    card_number      varchar
        unique,
    month_expiration varchar,
    year_expiration  varchar,
    cvv              integer,
    card_type        varchar,
    user_id          uuid references users (id) not null,
    available_money  integer
);