CREATE TABLE catalog_items (
       id bigint GENERATED BY DEFAULT AS IDENTITY,
       name VARCHAR NOT NULL,
       description VARCHAR NOT NULL,
       image varchar NOT NULL,
       category_id bigint,
       created_at TIMESTAMP DEFAULT NOW(),
       updated_at TIMESTAMP,
       FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);