CREATE TABLE Feedback(
     id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     user_id uuid REFERENCES Users(id) NOT NULL,
     message varchar NOT NULL,
     evaluation double precision NOT NULL
);