create table user_product
(
    order_number bigint generated by default as identity
        primary key,
    user_id      uuid
        references users (id),
    product_id   bigint
        references product
);
