CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    total_items INT NOT NULL CHECK (total_items > 0),
    total_price DECIMAL(10, 2) NOT NULL CHECK (total_price > 0),
    card_number VARCHAR(16) NOT NULL,
    payment_date TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'pending', -- (pending, paid, shipped, etc.)
    delivery_address TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);