create table organization
(
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique,
    description   varchar,
    inn           integer      not null,
    requisites    integer      not null,
    registrated_at timestamp    not null,
    creator_id    uuid unique not null
);


