create table file_links (
    id bigint PRIMARY KEY generated by default as identity,
    file_url text not null,
    file_name varchar not null,
    bucket_name VARCHAR(255) NOT NULL,
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expiry_date TIMESTAMP,
    status VARCHAR(50) DEFAULT 'active',
    extension varchar not null
);