create table notification(
                             id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY not null,
                             header varchar not null,
                             message varchar not null,
                             notified_at timestamp not null,
                             recipient uuid not null references users(id)
);
