create table public.product
(
    id             bigint generated by default as identity
        primary key,
    name           varchar                 not null
        unique,
    description    varchar                 not null
        unique,
    image          varchar                 not null,
    company_id     bigint                  not null,
    price          double precision        not null
        constraint product_price_check
            check (price > (0.0)::double precision),
    storage_amount integer                 not null,
    evaluation     double precision        not null,
    discount       integer
                                           references public.discount
                                               on delete set null,
    created_at     timestamp default now() not null,
    updated_at     timestamp
);
