create table organizationticket
(
    id         integer generated by default as identity
        primary key,
    creator_id uuid      not null
        unique,
    created_at timestamp not null,
    name       varchar(255),
    inn        integer   not null,
    requisites integer   not null
);


