create table "order"
(
    id bigint generated by default as identity primary key,
    item_number bigint references product (id) not null,
    quantity integer not null,
    user_id uuid references users (id) not null,
    created_date timestamp not null,
    last_modified_date timestamp
);