CREATE TABLE discounts (
           id bigint GENERATED BY DEFAULT AS IDENTITY,
           product_id bigint,
           category VARCHAR(100),
           discount_type VARCHAR(20) CHECK (discount_type IN ('PERCENT', 'FIXED', 'PROMO')),
           discount_value DECIMAL(10,2) NOT NULL CHECK (discount_value >= 0),
           promo_code VARCHAR(50) UNIQUE,
           start_date TIMESTAMP,
           end_date TIMESTAMP,
           is_active BOOLEAN DEFAULT FALSE
);