create table discount
(
    id int PRIMARY KEY generated by default as identity,
    product bigint not null unique,
    discount_size  integer not null,
    start_time timestamp not null,
    end_time timestamp not null
);