CREATE TABLE items (
       id bigint GENERATED BY DEFAULT AS IDENTITY,
       name VARCHAR NOT NULL,
       description VARCHAR NOT NULL,
       image varchar NOT NULL,
       company_id bigint NOT NULL,
       quantity INT NOT NULL CHECK (quantity >= 0),
       warehouse_location VARCHAR(100),
       created_at TIMESTAMP DEFAULT NOW(),
       updated_at TIMESTAMP
);

