create table reserve
(
    id          bigint generated by default as identity,
    product_id  bigint    not null,
    amount      integer   not null,
    reserved_by varchar   not null,
    reserved_at timestamp not null
);
