CREATE TABLE categories (
        id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
        name VARCHAR(255) NOT NULL UNIQUE,
        parent_id bigint,
        FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL
);