create table product
(
    id              bigint generated by default as identity
        primary key,
    name            varchar          not null
        unique,
    description     varchar          not null
        unique,
    image           varchar          not null,
    organization_id bigint           not null
        references organization,
    price           numeric          not null
        constraint product_price_check
            check ((price)::double precision > (0.0)::double precision),
    storage_amount  integer          not null,
    evaluation      double precision not null,
    discount int references discount(id) on delete set null
);