server:
  port: 8006

spring:
  application:
    name: Notification Microservice
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: ${POSTGRES_USERNAME}
    url: jdbc:postgresql://localhost:5432/NotificationMicroservice
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${MAILDEV_SPRING_MAIL_HOST}
    port: ${MAILDEV_SPRING_MAIL_PORT}
    username: ${MAILDEV_SPRING_MAIL_USERNAME}
    password: ${MAILDEV_SPRING_MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true