server:
  port: 8031

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Storage Service
  datasource:
    username: ${POSTGRES_USERNAME}
    url: jdbc:postgresql://localhost:5432/StorageService
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false