server:
  port: 8004

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Product Microservice
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}


security:
  jwt:
    secret: ${JWT_SECRET}
    expirationMs: 604800000 # 1 week