server:
  port: 8004

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Order Microservice
  datasource:
    username: ${POSTGRES_USERNAME}
    url: jdbc:postgresql://localhost:5432/OrderService
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false


security:
  jwt:
    secret: ${JWT_SECRET}
    expirationMs: 604800000 # 1 week
