server:
  port: 8030

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Catalog Service
  datasource:
    username: ${POSTGRES_USERNAME}
    url: jdbc:postgresql://localhost:5432/CatalogService
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints.web.exposure.include: 'prometheus, health, info'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true


security:
  jwt:
    secret: ${JWT_SECRET}
    expirationMs: 604800000 # 1 week