server:
  port: 8002

spring:
  application:
    name: Company Microservice
  datasource:
    username: ${POSTGRES_USERNAME}
    url: jdbc:postgresql://localhost:5432/CompanyMicroservice
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints.web.exposure.include: 'prometheus, health, info'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
