server:
  port: 8003

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Product Microservice
  datasource:
    username: "xparadize"
    url: jdbc:postgresql://localhost:5432/ProductMicroservice
    password: "password"
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      hibernate:
        ddl-auto: update
      show-sql: true

empty:
  product:
    filename:
      ${EMPTY_PRODUCT_FILENAME}