server:
  port: 8003

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Product Microservice
  datasource:
    username: ${POSTGRES_USERNAME}
    url: jdbc:postgresql://localhost:5432/ProductMicroservice
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

products:
  per:
    page:
      ${PRODUCTS_PER_PAGE}

empty:
  product:
    filename:
      ${EMPTY_PRODUCT_FILENAME}