global:
  scrape_interval: 5s

  external_labels:
    monitor: 'peolly-monitor'

scrape_configs:
  - job_name: 'peolly-market'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8001' ]
        labels:
          service: 'security-service'

      - targets: [ 'host.docker.internal:8002' ]
        labels:
          service: 'company-service'

      - targets: [ 'host.docker.internal:8030' ]
        labels:
          service: 'catalog-service'

      - targets: [ 'host.docker.internal:8031' ]
        labels:
          service: 'storage-service'

      - targets: [ 'host.docker.internal:8032' ]
        labels:
          service: 'pricing-service'

      - targets: [ 'host.docker.internal:8004' ]
        labels:
          service: 'order-service'

      - targets: [ 'host.docker.internal:8005' ]
        labels:
          service: 'payment-service'

      - targets: [ 'host.docker.internal:8006' ]
        labels:
          service: 'notification-service'

      - targets: [ 'host.docker.internal:8010' ]
        labels:
          service: 's3-server'
